name: 'Setup BrainCraft.io Workspace'
description: 'Sets up the complete multi-root workspace environment for BrainCraft.io using mise'
inputs:
  token:
    description: 'GitHub token for repository access'
    required: false
    default: ${{ github.token }}
  workspace-path:
    description: 'Path to clone the workspace'
    required: false
    default: 'workspace'
outputs:
  workspace-root:
    description: 'Path to the workspace root'
    value: ${{ steps.setup.outputs.workspace-root }}
runs:
  using: "composite"
  steps:
    - name: Clone workspace repository (root)
      uses: actions/checkout@v4
      with:
        repository: braincraftio/workspace
        path: ${{ inputs.workspace-path }}
        token: ${{ inputs.token }}
    
    - name: Setup mise and clone repositories
      id: setup
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        cd ${{ inputs.workspace-path }}
        
        # Set output for workspace root
        echo "workspace-root=$PWD" >> $GITHUB_OUTPUT
        
        # Trust mise configuration
        mise trust --all
        
        # Install all tools
        mise install
        
        # Clone all child repositories using mise
        mise run git:clone
        
        # Verify setup
        echo "=== Workspace Structure ==="
        ls -la
        
        echo "=== Repository Status ==="
        mise run git:status || true
        
        echo "=== Available Mise Tasks ==="
        mise tasks || true